spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/HackerMan/config-server-git
server:
  port: 1201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/