server:
  port: 2222

spring:
  application:
    name: stream-mq
  rabbitmq:
    host: 112.74.57.197
    port: 5672
    username: lyq
    password: 92932266
  cloud:
    stream:
      bindings:
        input:
          group: Service-A
          destination: greetings
